apiVersion: v1
kind: Service
metadata:
  namespace: spark-jobs
  name: dbt-project-demo-service
  labels:
    app: dbt-project-demo
spec:
  selector:
    app: dbt-project-demo
  type: LoadBalancer
  loadBalancerIP: 192.168.1.165
  ports:
    - name: docs-webserver
      port: 8080
      targetPort: docs-webserver
      protocol: TCP
