# ======
# Project Details
# ======
name: 'ktl_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'ktl_dbt'

# ======
# File Path Configs
# ======
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["target"]

# directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# ==================
# Variable Configs
# ==================
vars:
  # ref_eod_table: name of table that raw vault models get EOD time from, it should have 4 columns cob_date, last_cob_date, run_time, last_run_time
  # initial_cob_date: cob date value that raw vault models will use to query run_time for initial load
  #                   if not specify, query the latest run_time
  # cob_date: cob date value that raw vault models will use to query run_time as incre_end_date, and last_run_time as incre_start_date for incremental load
  #           if not specify, query the latest run_time
  # if not specify ref_eod_table, use 3 vars initial_date, incre_start_date, incre_end_date instead
  ref_eod_table: vw_ref_eod
  initial_cob_date: "2024-11-04"
  # cob_date: 

  # start date of raw vault batch initial load
  # initial_date: "2024-01-01"
  
  # start date value for EOD (default: no start date or 1900-01-01)
  # incre_start_date: "2020-01-01"

  # end date value for EOD (default: current date)
  # incre_end_date: 

  dv_hash_method: sha256
  dv_hash_key_dtype: binary
  
  # all of data vault column system
  dv_system:
    columns:
      - target: dv_kaf_ldt
        dtype: timestamp
        description: 'Thời điểm dữ liệu được load từ kafka'
        source:
          name: ktime
          dtype: timestamp

      - target: dv_kaf_ofs
        dtype: bigint
        description: 'số offset của kafka'
        source:
          name: koffset
          dtype: bigint

      - target: dv_cdc_ops
        dtype: string
        description: 'loại CDC (change data capture) bao gồm :"R"="read", "I"="insert", "U"="update" và "D"="delete"'
        source:
          name: cdc_operation
          dtype: string

      - target: dv_src_ldt
        dtype: timestamp
        description: 'Thời điểm dữ liệu được insert từ source'
        source:
          name: optime
          dtype: timestamp

      - target: dv_src_rec
        dtype: string
        description: 'Tên bảng source của dữ liệu'
        source:
          name: record_source
          dtype: string

      - target: dv_ldt
        dtype: timestamp
        description: 'Thời điểm dữ liệu được load từ vùng raw vault'
        source:
          name: current_timestamp()
          dtype: timestamp

  catalog_table:
    ref_group:
    - name: mdm_phone_number_prefix
      column_old_phone: old_phone
      column_new_phone: new_phone

    - name: mdm_catalog_category
      column_source: source
      column_category_type: category_type
      column_original_value: original_value
      column_standard_value: standard_value

models:
  ktl_dbt:
    # Config indicated by + and applies to all files under models/example/
    integration_demo:
      +materialized: incremental
      +file_format: iceberg
      +tblproperties:
        "hive.engine.enabled": "true"
        "read.parquet.vectorization.enabled": "true"
        "read.parquet.vectorization.batch-size": "10000"

      raw_vault:
        stream:
          +materialized: streaming
          +submission_method: spark_session
          +streaming_checkpoint_path: "s3a://data/tmp/checkpoint/dbt_project_demo"
        batch:
          +materialized: incremental
          # +submission_method: spark_session
          # +streaming_checkpoint_path: "s3a://data/tmp/checkpoint/dbt_project_demo"

      biz_vault:
          +materialized: table

    mdm:
      +materialized: table
      +file_format: iceberg
      +tblproperties:
        "hive.engine.enabled": "true"
        "read.parquet.vectorization.enabled": "true"
        "read.parquet.vectorization.batch-size": "10000"

seeds:
  ktl_dbt:
    +schema: source
    +file_format: iceberg
